monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - my_application
        - hermes # TODO - move to bundle

when@dev:
    monolog:
        handlers:
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
                verbosity_levels:
                    VERBOSITY_NORMAL: debug
