services:
    Mmalessa\Hermes\Receiver\HttpReceiver\HttpReceiverFactory:
        tags: ['hermes.receiver_factory']
        arguments:
            $logger: '@monolog.logger.hermes'

    Mmalessa\Hermes\Receiver\KafkaReceiver\KafkaReceiverFactory:
        tags: ['hermes.receiver_factory']

    Mmalessa\Hermes\Console\:
        resource: '../../Console/*'
        tags: ['console.command']
        autoconfigure: true
        bind:
            $logger: '@monolog.logger.hermes'
            $container: '@service_container'
